version: '3.8'

services:
  # 1. Service cho Database (SQL Server)
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: mssql-container
    environment:
      
      SA_PASSWORD: "MinhMinh@1234" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      # Save data in database when container is removed
      - sql-data:/var/opt/mssql

  # 2. Service cho Spring Boot (Backend)
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    environment:
      # Kết nối đến service database bằng tên service 'sql-server'
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sql-server:1433;databaseName=IntelligentSystemDB;encrypt=false;"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "MinhMinh@1234" 
    depends_on:
      - sql-server 
  # 3. Service cho React (Frontend)
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-container
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-app 
    
volumes:
  sql-data: